export type GridSortDirection = 'asc' | 'desc';

export type GridFilterOperator =
  | 'eq'
  | 'ne'
  | 'contains'
  | 'startsWith'
  | 'endsWith'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'in'
  | 'sameDay';

export interface GridFilter {
  field: string;
  operator: GridFilterOperator;
  value: unknown;
}

/**
 * Global-search request produced by the DataGrid.
 *
 * `conditions` are OR-ed together. This preserves the historic DataGrid
 * behavior where the same search text was translated per searchable column
 * (for example: string contains OR numeric equality).
 *
 * Column filters remain separate in `GridLoadRequest.filters` and are AND-ed.
 */
export interface GridSearch {
  value: string;
  conditions: GridFilter[];
}

export interface GridSort {
  field: string;
  direction: GridSortDirection;
}

/**
 * Provider-neutral request generated by the DataGrid.
 *
 * `continuation` is intentionally opaque: a provider may use an offset,
 * cursor, page token or any other backend-specific continuation state.
 *
 * `search.conditions` represent one global OR group.
 * `filters` represent explicit column/base filters combined with AND semantics.
 */
export interface GridLoadRequest {
  pageSize: number;
  continuation?: unknown;
  search?: GridSearch;
  filters?: GridFilter[];
  sort?: GridSort[];
}

/**
 * Provider-neutral page returned to the DataGrid.
 */
export interface GridPage<T> {
  items: T[];
  hasMore: boolean;
  continuation?: unknown;
  totalCount?: number;
}

/**
 * Minimal contract required by a remote DataGrid data source.
 * Backend and transport details belong to concrete provider implementations.
 */
export interface GridDataProvider<T> {
  load(request: GridLoadRequest): Promise<GridPage<T>>;

  create?(data: Partial<T>): Promise<T>;
  update?(data: T): Promise<T>;
  delete?(data: T): Promise<void>;
}
