export type GridSortDirection = 'asc' | 'desc';

export type GridFilterOperator =
  | 'eq'
  | 'ne'
  | 'contains'
  | 'startsWith'
  | 'endsWith'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'in';

export interface GridFilter {
  field: string;
  operator: GridFilterOperator;
  value: unknown;
}

export interface GridSort {
  field: string;
  direction: GridSortDirection;
}

/**
 * Provider-neutral request generated by the DataGrid.
 *
 * `continuation` is intentionally opaque: a provider may use an offset,
 * cursor, page token or any other backend-specific continuation state.
 */
export interface GridLoadRequest {
  pageSize: number;
  continuation?: unknown;
  search?: string;
  filters?: GridFilter[];
  sort?: GridSort[];
}

/**
 * Provider-neutral page returned to the DataGrid.
 */
export interface GridPage<T> {
  items: T[];
  hasMore: boolean;
  continuation?: unknown;
  totalCount?: number;
}

/**
 * Minimal contract required by a remote DataGrid data source.
 * Backend and transport details belong to concrete provider implementations.
 */
export interface GridDataProvider<T> {
  load(request: GridLoadRequest): Promise<GridPage<T>>;

  create?(data: Partial<T>): Promise<T>;
  update?(data: T): Promise<T>;
  delete?(data: T): Promise<void>;
}
